# Site settings
title: I Code Things
email: matt@icodethin.gs
description: Personal Website of Matthew Vandenbossche
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://icodethin.gs" # the base hostname & protocol for your site
twitter_username: matt_v
github_username:  icodethings
timezone: Australia/Melbourne

# Build settings
markdown: kramdown

paginate: 5
permalink: pretty
relative_permalinks: true