# Site settings
title: I Code Things
email: matt@icodethin.gs
tagline: Matthew Vandenbossche
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://icodethin.gs" # the base hostname & protocol for your site
twitter_username: matt_v
github_username:  icodethings
timezone: Australia/Melbourne

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

paginate: 5
permalink: pretty
excerpt_separator: <!--more-->

# SEO
twitter:
  username: matt_v
author:
  twitter: matt_v
  picture: https://avatars2.githubusercontent.com/u/3532069

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
